FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git curl ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY services/video-translation/requirements.txt requirements.txt
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt
COPY services/video-translation/main.py main.py

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]